# Generated by Django 2.1.8 on 2019-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Vendedor'), (3, 'Cliente online'), (4, 'Por definir')], default=3),
        ),
    ]
