# Generated by Django 2.1.8 on 2019-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20190815_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'cliente_online'), (3, 'vendedor_tpv')], default=1, primary_key=True, serialize=False),
        ),
    ]
