# Generated by Django 2.1.8 on 2019-08-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20190819_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (3, 'vendedor_tpv'), (2, 'cliente_online')], default=1, primary_key=True, serialize=False),
        ),
    ]
