# Generated by Django 2.1.8 on 2019-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_auto_20190819_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'vendedor_tpv'), (3, 'cliente_online')], default=3, primary_key=True, serialize=False),
        ),
    ]
