version: '3'
services:
  postgres:
    container_name: saas_pg
    image: postgres:11.4
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multitenant
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./_datos_iniciales:/home/_datos_iniciales
    restart: unless-stopped
  
  web:
    container_name: saas_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  pgadmin:
    container_name: saas_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: