# Generated by Django 2.1.8 on 2019-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamentos',
            fields=[
                ('idMedicamentos', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
            ],
        ),
    ]
