# Generated by Django 2.1.8 on 2019-08-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
