# Generated by Django 2.1.8 on 2019-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('imagen', models.URLField(max_length=255)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
