# Generated by Django 2.1.8 on 2019-08-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
