# Generated by Django 2.1.8 on 2019-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=30)),
                ('fechaCreacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
